#!/bin/bash

LOGFILE=/dev/stderr
TRANSPORT_PACKAGES="apt-transport-https ca-certificates software-properties-common"
DOCKER_VERSION=18.06

function log() {
    datestring=`date +"%Y-%m-%d %H:%M:%S"`
    echo -e "$datestring - $@" | tee $LOGFILE
}


# enforce docker version
function get_docker() {
    log "Started get_docker"
    apt-get update
    dpkg -l software-properties-common | grep ^ii || apt-get install ${TRANSPORT_PACKAGES} -y
    curl --retry 10 -fssl https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get -y install docker-ce="${DOCKER_VERSION}*"
    apt-get install -y socat conntrack ipset
    log "started finished_docker"
}


function get_gitlab_worker() {
    apt-get update
    dpkg -l software-properties-common | grep ^ii || apt-get install ${TRANSPORT_PACKAGES} -y
    curl --retry 10 -fssl https://packages.gitlab.com/gpg.key | apt-key add -
    cat << EOF > /etc/apt/sources.list.d/runner_gitlab-runner.list
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/runner/gitlab-runner

deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ xenial main
deb-src https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ xenial main
EOF
    apt-get update
    apt-get install -y gitlab-runner
}


function register_worker() {
     /usr/bin/gitlab-runner \
          register \
          --non-interactive \
          --name "${WORKER}" \
          --url "https://gitlab.com/ci" \
          --registration-token "${RUNNER_TOKEN}" \
          --executor "docker" \
          --docker-privileged \
          --docker-image "debian:latest" \
          --tag-list "docker,privileged" \
          --run-untagged \
          --locked
}


function enable_service() {
    cat /etc/gitlab-runner/config.toml
    sed -i  's/concurrent = 1/concurrent = 4/' /etc/gitlab-runner/config.toml
    cat /etc/gitlab-runner/config.toml
    systemctl enable gitlab-runner
    systemctl restart gitlab-runner
}


function main() {
    for i in $(seq 1 10); do get_docker && break; sleep 30; done;
    for i in $(seq 1 10); do get_gitlab_worker && break; sleep 30; done;
    register_worker
    enable_service
}

# This line and the if condition bellow allow sourcing the script without executing
# the main function
(return 0 2>/dev/null) && sourced=1 || sourced=0

if [[ $sourced == 1 ]]; then
    set +e
    echo "You can now use any of these functions:"
    echo ""
    typeset -F |  cut -d" " -f 3
else
    set -eu
    cd /root
    iptables -P FORWARD ACCEPT
    swapoff -a
    main "$@"
fi

